version: '3.8'

services:
  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - order_service
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  user_service:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    depends_on:
      user_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@user_db:5432/user_service_db

  order_service:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    depends_on:
      order_db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@order_db:5432/order_service_db

  user_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=user_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - user_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  order_db:
    image: postgres:13
    environment:
      - POSTGRES_DB=order_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - order_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery_worker:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    command: celery -A api_gateway.celery worker -l info
    depends_on:
      - redis
      - user_service
      - order_service
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

volumes:
  user_data:
  order_data:
  redis_data: