# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: order_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'order_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13order_service.proto\x12\rorder_service\"q\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\'\n\x05items\x18\x03 \x03(\x0b\x32\x18.order_service.OrderItem\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x12\n\ncreated_at\x18\x05 \x01(\t\"@\n\tOrderItem\x12\x12\n\nproduct_id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\x12\r\n\x05price\x18\x03 \x01(\x02\"\x1a\n\x0cOrderRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"$\n\x11UserOrdersRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"C\n\rOrderResponse\x12#\n\x05order\x18\x01 \x01(\x0b\x32\x14.order_service.Order\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"1\n\tOrderList\x12$\n\x06orders\x18\x01 \x03(\x0b\x32\x14.order_service.Order2\xe2\x01\n\x0cOrderService\x12\x41\n\x0b\x43reateOrder\x12\x14.order_service.Order\x1a\x1c.order_service.OrderResponse\x12\x45\n\x08GetOrder\x12\x1b.order_service.OrderRequest\x1a\x1c.order_service.OrderResponse\x12H\n\nListOrders\x12 .order_service.UserOrdersRequest\x1a\x18.order_service.OrderListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ORDER']._serialized_start=38
  _globals['_ORDER']._serialized_end=151
  _globals['_ORDERITEM']._serialized_start=153
  _globals['_ORDERITEM']._serialized_end=217
  _globals['_ORDERREQUEST']._serialized_start=219
  _globals['_ORDERREQUEST']._serialized_end=245
  _globals['_USERORDERSREQUEST']._serialized_start=247
  _globals['_USERORDERSREQUEST']._serialized_end=283
  _globals['_ORDERRESPONSE']._serialized_start=285
  _globals['_ORDERRESPONSE']._serialized_end=352
  _globals['_ORDERLIST']._serialized_start=354
  _globals['_ORDERLIST']._serialized_end=403
  _globals['_ORDERSERVICE']._serialized_start=406
  _globals['_ORDERSERVICE']._serialized_end=632
# @@protoc_insertion_point(module_scope)
