# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'user_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x0cuser_service\"E\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"?\n\x0cUserResponse\x12 \n\x04user\x18\x01 \x01(\x0b\x32\x12.user_service.User\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"-\n\x08UserList\x12!\n\x05users\x18\x01 \x03(\x0b\x32\x12.user_service.User\"\x07\n\x05\x45mpty2\xc7\x01\n\x0bUserService\x12<\n\nCreateUser\x12\x12.user_service.User\x1a\x1a.user_service.UserResponse\x12@\n\x07GetUser\x12\x19.user_service.UserRequest\x1a\x1a.user_service.UserResponse\x12\x38\n\tListUsers\x12\x13.user_service.Empty\x1a\x16.user_service.UserListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=36
  _globals['_USER']._serialized_end=105
  _globals['_USERREQUEST']._serialized_start=107
  _globals['_USERREQUEST']._serialized_end=132
  _globals['_USERRESPONSE']._serialized_start=134
  _globals['_USERRESPONSE']._serialized_end=197
  _globals['_USERLIST']._serialized_start=199
  _globals['_USERLIST']._serialized_end=244
  _globals['_EMPTY']._serialized_start=246
  _globals['_EMPTY']._serialized_end=253
  _globals['_USERSERVICE']._serialized_start=256
  _globals['_USERSERVICE']._serialized_end=455
# @@protoc_insertion_point(module_scope)
